version: '3'
services:
  api:
    image: jaimax/800smellit-api
    build:
      context: .
    env_file:
      - apps/api/.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jaimin
      - MONGO_INITDB_ROOT_PASSWORD=800smellit
    volumes:
      - mongo-db:/data/db # persist mongodb data in a named volume

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api

# declare named volumes
volumes:
  mongo-db:
